admin:
    backendroles:
        - admin
    host:
        - "*"
    users:
        - elastic

kibana_user:
    backendroles:
        - kibana_user
    host:
        - "*"
    users:
        - kibana

read_only_user:
    backendroles:
        - read_only_user
    host:
        - "*"
    users:
        - read_only

logstash_user:
    backendroles:
        - logstash_user
    host:
        - "*"
    users:
        - logstash

beats_user:
    backendroles:
        - beats_user
    host:
        - "*"
    users:
        - beats

monitoring_user:
    backendroles:
        - monitoring_user
        - alerting
    host:
        - "*"
    users:
        - monitoring

manage_snapshots:
    backendroles:
        - manage_snapshots
    host:
        - "*"
    users:
        - elastic

reader_user:
    backendroles:
        - reader_user
    host:
        - "*"
    users:
        - reader

app_user:
    backendroles:
        - app_user
    host:
        - "*"
    users:
        - app
