cluster.name: ${CLUSTER_NAME}

node:
  name: ${HOSTNAME}
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}

#values are inverted ###aws## means actually to remove this section when building for aws 
###aws###
network:
  host:
  - 0.0.0.0

cloud:
  gce:
    project_id: ${PROJECT_ID}
    zone: ${ZONE}

discovery:
  zen:
    hosts_provider: gce
    minimum_master_nodes: ${MINIMUM_MASTER_NODES}
  gce:
    tags: ${TAGS}
###aws###

#values are inverted ###gce## means actually to remove this section when building for gce 
###gce###
network:
  host:
  - 0.0.0.0
  publish_host: _ec2:privateIp_

discovery:
  zen:
    hosts_provider: ec2
  ec2:
    tag:
      ElasticSearch: ${TAGS}
    endpoint: ec2.${ZONE}.amazonaws.com

s3:
  client:
    default:
      endpoint: s3.${ZONE}.amazonaws.com
cloud.node.auto_attributes: true
cluster.routing.allocation.awareness.attributes: aws_availability_zone
###gce###



http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

xpack.graph.enabled: false
xpack.ml.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.watcher.enabled: true
xpack.monitoring.collection.enabled: true

searchguard:
    ssl.transport:
        enabled: true
        enable_openssl_if_available: true
        keystore_type: JKS
        keystore_filepath: searchguard/ssl/${NODE_NAME}-keystore.jks
        keystore_password: ${KS_PWD}
        truststore_type: JKS
        truststore_filepath: searchguard/ssl/truststore.jks
        truststore_password: ${TS_PWD}
        enforce_hostname_verification: false
    ssl.http:
        enabled: ${HTTP_SSL}
        clientauth_mode: OPTIONAL
        enable_openssl_if_available: true
        keystore_type: JKS
        keystore_filepath: searchguard/ssl/${NODE_NAME}-keystore.jks
        keystore_password: ${KS_PWD}
        truststore_type: JKS
        truststore_filepath: searchguard/ssl/truststore.jks
        truststore_password: ${TS_PWD}
    authcz.admin_dn:
      - "CN=elastic ,OU=devops, C=COM"
    enable_snapshot_restore_privilege: true
    enterprise_modules_enabled: ${ENTERPRISE_ENABLED}
